import { test, expect } from '@playwright/test';
const identity = { germanName: 'Rose', englishName: 'Rose', latinName: 'Rosa' };
const info = { haltbarkeit: '7 Tage', kombiniertMit: 'Grün', verarbeitung: 'Anschneiden', verwendung: 'Strauß' };
for (const type of ['image/jpeg', 'image/png', 'image/webp']) test(`${type} upload, replace, save, reload, backup and delete`, async ({ page }) => {
  const backups: any[] = [];
  await page.route('**/api/backup', route => { backups.push(route.request().postDataJSON()); return route.fulfill({ json: { enabled: true, cards: [] } }); });
  await page.route('**/api/search', route => { expect(route.request().postDataJSON().skipImages).toBe(true); return route.fulfill({ json: { identity, photos: [], usedQuery: '' } }); });
  await page.route('**/api/card', route => route.fulfill({ json: { ...identity, ...info } }));
  await page.goto('/'); await page.getByRole('button', { name: 'Neue Karte' }).click();
  await page.getByLabel('Blumenname', { exact: true }).fill('Rose');
  await page.getByRole('checkbox').check(); await page.getByRole('button', { name: 'Suchen', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Eigenes Foto hochladen', exact: true })).toBeVisible();
  const base64 = await page.evaluate(type => { const canvas = document.createElement('canvas'); canvas.width = 8; canvas.height = 8; canvas.getContext('2d')!.fillRect(0, 0, 8, 8); return canvas.toDataURL(type).split(',')[1]; }, type);
  const input = page.locator('input[type=file]');
  await input.setInputFiles({ name: 'unsupported.txt', mimeType: 'text/plain', buffer: Buffer.from('text') });
  await expect(page.locator('main').getByRole('alert')).toContainText('JPEG-, PNG- oder WebP');
  await input.setInputFiles({ name: 'large.png', mimeType: 'image/png', buffer: Buffer.alloc(10 * 1024 * 1024 + 1) });
  await expect(page.locator('main').getByRole('alert')).toContainText('Maximal 10 MB');
  await input.setInputFiles({ name: 'photo', mimeType: type, buffer: Buffer.from(base64, 'base64') });
  await expect(page.locator('.photo-option.selected img')).toBeVisible();
  const first = await page.locator('.photo-option.selected img').getAttribute('src');
  await input.setInputFiles({ name: 'replacement', mimeType: type, buffer: Buffer.from(base64, 'base64') });
  await expect(page.locator('.photo-option.selected img')).not.toHaveAttribute('src', first!);
  await page.getByRole('button', { name: 'Karte erstellen', exact: true }).click();
  await page.getByRole('button', { name: 'Speichern', exact: true }).click();
  await expect.poll(() => backups.find(body => body.action === 'save')?.card.imageSource).toBe('upload');
  expect(backups.find(body => body.action === 'save').card.imageUrl).toMatch(/^\/api\/images\/[a-f0-9]{64}\./);
  await page.reload();
  const image = page.locator('.library-grid img'); await expect(image).toBeVisible();
  await expect.poll(() => image.evaluate((img: HTMLImageElement) => img.complete && img.naturalWidth > 0)).toBe(true);
  await page.getByRole('button', { name: 'Löschen', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Löschen', exact: true }).click();
  await expect.poll(() => backups.some(body => body.action === 'delete')).toBe(true);
  await page.reload(); await expect(page.locator('.library-grid article')).toHaveCount(0);
});
